name: sentiment_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas=1.5.3
  - numpy=1.23.5
  - pyarrow=12.0.1
  - pip:
     - pandas==1.5.3
     - numpy==1.23.5
     - pyarrow==12.0.1
     - nltk==3.8.1
     - textblob==0.17.1
